pre_install() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_install() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  mandb -sqp
}

pre_upgrade() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  mandb -sqp
}

pre_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
